# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4feccd5b05054a5d1725c1997f09acb4df51066bb8d1788edff23631aab29ab5fb800e16a91aba5560c8ffcd162aa39126f6158a8b3cea15060ee9f9e0d9b91

test:
  secret_key_base: 4946e03ab550f2c03698cae5ef80eba6ada817ef56604f13b3690c2ae1cb9945077214ff1c1d56c6de396f618ffe9b7f3f7b643b7917502d96636465a03c64f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
